export const SHARED_AUTHENTICATION_STARTED = 'SHARED_AUTHENTICATION_STARTED';
export const SHARED_AUTHENTICATION_FAILED = 'SHARED_AUTHENTICATION_FAILED';
export const SHARED_AUTHENTICATION_TOKEN_RECEIVED = 'SHARED_AUTHENTICATION_TOKEN_RECEIVED';
export const SHARED_AUTHENTICATION_INVALIDATE_TOKEN = 'SHARED_AUTHENTICATION_INVALIDATE_TOKEN';

export const SHARED_DISMISS_ERROR = 'SHARED_DISMISS_ERROR';
export const SHARED_REGISTRATION_STARTED = 'SHARED_REGISTRATION_STARTED';
export const SHARED_REGISTRATION_FAILED = 'SHARED_REGISTRATION_FAILED';
export const SHARED_REGISTRATION_FINISHED = 'SHARED_REGISTRATION_FINISHED';

export const FETCH_CHANNELS_STARTED = 'FETCH_CHANNELS_STARTED';
export const FETCH_CHANNELS_FINISHED = 'FETCH_CHANNELS_FINISHED';
export const FETCH_CHANNELS_FAILED = 'FETCH_CHANNELS_FAILED';
export const CREATE_CHANNEL_STARTED = 'CREATE_CHANNEL_STARTED';
export const CREATE_CHANNEL_FINISHED = 'CREATE_CHANNEL_FINISHED';
export const CREATE_CHANNEL_FAILED = 'CREATE_CHANNEL_FAILED';
export const DELETE_CHANNEL_STARTED = 'DELETE_CHANNEL_STARTED';
export const DELETE_CHANNEL_FINISHED = 'DELETE_CHANNEL_FINISHED';
export const DELETE_CHANNEL_FAILED = 'DELETE_CHANNEL_FAILED';
export const RENAME_CHANNEL_STARTED = 'RENAME_CHANNEL_STARTED';
export const RENAME_CHANNEL_FINISHED = 'RENAME_CHANNEL_FINISHED';
export const RENAME_CHANNEL_FAILED = 'RENAME_CHANNEL_FAILED';
export const CHANNEL_INVITE_USER_FAILED = 'CHANNEL_INVITE_USER_FAILED';
export const CHANNEL_INVITE_USER_FINISHED = 'CHANNEL_INVITE_USER_FINISHED';

export const MESSAGE_CREATE = 'MESSAGE_CREATE';
export const MESSAGE_DELETE = 'MESSAGE_DELETE';
export const MESSAGE_UPVOTE = 'MESSAGE_UPVOTE';
export const MESSAGE_DOWNVOTE = 'MESSAGE_DOWNVOTE';

export const PROFILE_CHANGE_NAME = 'PROFILE_CHANGE_NAME';
export const PROFILE_UPLOAD_PICTURE = 'PROFILE_UPLOAD_PICTURE';