export const SHARED_AUTHENTICATION_STARTED = 'SHARED_AUTHENTICATION_STARTED';
export const SHARED_AUTHENTICATION_FAILED = 'SHARED_AUTHENTICATION_FAILED';
export const SHARED_AUTHENTICATION_TOKEN_RECEIVED = 'SHARED_AUTHENTICATION_TOKEN_RECEIVED';
export const SHARED_AUTHENTICATION_INVALIDATE_TOKEN = 'SHARED_AUTHENTICATION_INVALIDATE_TOKEN';

export const SHARED_DISMISS_ERROR = 'SHARED_DISMISS_ERROR';
export const SHARED_REGISTRATION_STARTED = 'SHARED_REGISTRATION_STARTED';
export const SHARED_REGISTRATION_FAILED = 'SHARED_REGISTRATION_FAILED';
export const SHARED_REGISTRATION_FINISHED = 'SHARED_REGISTRATION_FINISHED';

export const CHANNELS_FETCH_STARTED = 'CHANNELS_FETCH_STARTED';
export const CHANNELS_FETCH_FINISHED = 'CHANNELS_FETCH_FINISHED';
export const CHANNELS_FETCH_FAILED = 'CHANNELS_FETCH_FAILED';
export const CHANNEL_CREATE_STARTED = 'CHANNEL_CREATE_STARTED';
export const CHANNEL_CREATE_FINISHED = 'CHANNEL_CREATE_FINISHED';
export const CHANNEL_CREATE_FAILED = 'CHANNEL_CREATE_FAILED';
export const CHANNEL_DELETE_STARTED = 'CHANNEL_DELETE_STARTED';
export const CHANNEL_DELETE_FINISHED = 'CHANNEL_DELETE_FINISHED';
export const CHANNEL_DELETE_FAILED = 'CHANNEL_DELETE_FAILED';
export const CHANNEL_RENAME_STARTED = 'CHANNEL_RENAME_STARTED';
export const CHANNEL_RENAME_FINISHED = 'CHANNEL_RENAME_FINISHED';
export const CHANNEL_RENAME_FAILED = 'CHANNEL_RENAME_FAILED';
export const CHANNEL_INVITE_USER_FAILED = 'CHANNEL_INVITE_USER_FAILED';
export const CHANNEL_INVITE_USER_FINISHED = 'CHANNEL_INVITE_USER_FINISHED';

export const MESSAGES_FETCH_STARTED = 'MESSAGES_FETCH_STARTED';
export const MESSAGES_FETCH_FINISHED = 'MESSAGES_FETCH_FINISHED';
export const MESSAGES_FETCH_FAILED = 'MESSAGES_FETCH_FAILED';
export const MESSAGE_SEND_STARTED = 'MESSAGE_SEND_STARTED';
export const MESSAGE_SEND_FINISHED = 'MESSAGE_SEND_FINISHED';
export const MESSAGE_SEND_FAILED = 'MESSAGE_SEND_FAILED';
export const MESSAGE_DELETE_STARTED = 'MESSAGE_DELETE_STARTED';
export const MESSAGE_DELETE_FAILED = 'MESSAGE_DELETE_FAILED';
export const MESSAGE_DELETE_FINISHED = 'MESSAGE_DELETE_FINISHED';
export const MESSAGE_UPVOTE = 'MESSAGE_UPVOTE';
export const MESSAGE_DOWNVOTE = 'MESSAGE_DOWNVOTE';

export const PROFILE_DETAILS_FETCH_STARTED = 'PROFILE_DETAILS_FETCH_STARTED';
export const PROFILE_DETAILS_FETCH_FAILED = 'PROFILE_DETAILS_FETCH_FAILED';
export const PROFILE_AVATAR_FETCH_STARTED = 'PROFILE_AVATAR_FETCH_STARTED';
export const PROFILE_AVATAR_FETCH_FAILED = 'PROFILE_AVATAR_FETCH_FAILED';
export const PROFILE_AVATAR_FETCH_FINISHED = 'PROFILE_AVATAR_FETCH_FINISHED';
export const PROFILE_DETAILS_UPDATE_STARTED = 'PROFILE_DETAILS_UPDATE_STARTED';
export const PROFILE_DETAILS_UPDATE_FAILED = 'PROFILE_DETAILS_UPDATE_FAILED';
export const PROFILE_AVATAR_UPDATE_STARTED = 'CHANGE_PROFILE_NAME_STARTED';
export const PROFILE_AVATAR_UPDATE_FAILED = 'CHANGE_PROFILE_NAME_FAILED';
export const PROFILE_DETAILS_UPDATE = 'PROFILE_DETAILS_UPDATE';
export const PROFILE_AVATAR_UPDATE = 'PROFILE_AVATAR_UPDATE';
