export const SHARED_AUTHENTICATION_STARTED = 'SHARED_AUTHENTICATION_STARTED';
export const SHARED_AUTHENTICATION_FAILED = 'SHARED_AUTHENTICATION_FAILED';
export const SHARED_AUTHENTICATION_TOKEN_RECEIVED = 'SHARED_AUTHENTICATION_TOKEN_RECEIVED';
export const SHARED_AUTHENTICATION_INVALIDATE_TOKEN = 'SHARED_AUTHENTICATION_INVALIDATE_TOKEN';
export const SHARED_DISMISS_ERROR = 'SHARED_DISMISS_ERROR';
export const SHARED_REGISTRATION_STARTED = 'SHARED_REGISTRATION_STARTED';
export const SHARED_REGISTRATION_FAILED = 'SHARED_REGISTRATION_FAILED';
export const SHARED_REGISTRATION_FINISHED = 'SHARED_REGISTRATION_FINISHED';

export const FETCH_CHANNELS_STARTED = 'FETCH_CHANNELS_STARTED';
export const FETCH_CHANNELS_FINISHED = 'FETCH_CHANNELS_FINISHED';
export const FETCH_CHANNELS_FAILED = 'FETCH_CHANNELS_FAILED';
export const CHANNEL_CREATE = 'CHANNEL_CREATE';
export const CHANNEL_DELETE = 'CHANNEL_DELETE';
export const CHANNEL_RENAME = 'CHANNEL_RENAME';
export const CHANNEL_INVITE_USER = 'CHANNEL_INVITE_USER';

export const MESSAGE_CREATE = 'MESSAGE_CREATE';
export const MESSAGE_DELETE = 'MESSAGE_DELETE';
export const MESSAGE_UPVOTE = 'MESSAGE_UPVOTE';
export const MESSAGE_DOWNVOTE = 'MESSAGE_DOWNVOTE';

export const PROFILE_CHANGE_NAME = 'PROFILE_CHANGE_NAME';
export const PROFILE_UPLOAD_PICTURE = 'PROFILE_UPLOAD_PICTURE';